### ISSUE TITLE
⚠️ Deployment got hacked!

### ISSUE THREAD

**Issue by n-ce** [scalar-dev/beampipe#107]
I am very sad to say this but it seems Beampipe.io is hacked on all links is returning a grey page. And the js tracker is returning a 33kb code containing google ad and what not. This is a really scary situation!

**Comment by roadToCoder** [comment]
Same here, deleted the script while waiting for more information

**Comment by alexsparrow** [comment]
Thanks very much for the heads up and apologies for the alarm. I believe this was actually me forgetting to renew the domain :-(  I suspect the ad was coming from the domain parking page. It is renewed now so service should be restored.  

Unfortunately, as is probably obvious, I haven't had a lot of time to work on beampipe lately.

Closing for now but let me know if any further issues.
